"""Notion schema constants.

AUTO-GENERATED by scripts/gen_schema.py — do not edit manually.
Edit schema.yaml and run: python scripts/gen_schema.py
"""

# fmt: off

class PROPS:
    """Top-level Workout Log property names."""
    WORKOUT_NAME = "Workout Name"
    DATE = "Date"
    DAY_TYPE = "Day Type"
    DURATION = "Duration"
    DIFFICULTY = "Difficulty"
    ENERGY = "Energy"
    KNEE_COMFORT = "Knee Comfort"
    MOOD = "Mood"
    SAUNA = "Sauna"
    WORKOUT_NOTES = "Workout Notes"

class TRACK:
    """Weight Tracking Log child database column names."""
    EXERCISE = "Exercise"
    SUGGESTED = "Suggested"
    SETS_X_REPS = "Sets x Reps"
    SET_1 = "Set 1"
    SET_2 = "Set 2"
    SET_3 = "Set 3"
    SET_4 = "Set 4"
    NOTES = "Notes"
    SET_COLS: tuple[str, ...] = ("Set 1", "Set 2", "Set 3", "Set 4",)

class DAY_LABELS:
    """Notion Day Type select values (key → notion select name)."""
    MONDAY = "Monday - Upper Push"
    TUESDAY = "Tuesday - Lower Body"
    THURSDAY = "Thursday - Upper Pull"
    SUNDAY = "Sunday - Bachata"

class EnergyValues:
    """Allowed select values for 'Energy'."""
    HIGH = "⚡ High"
    MEDIUM = "😐 Medium"
    LOW = "😴 Low"

class KneeComfortValues:
    """Allowed select values for 'Knee Comfort'."""
    NO_PAIN = "✅ No pain"
    MILD_DISCOMFORT = "⚠️ Mild discomfort"
    PAIN = "🛑 Pain"

class MoodValues:
    """Allowed select values for 'Mood'."""
    GREAT = "😊 Great"
    GOOD = "😌 Good"
    NEUTRAL = "😐 Neutral"
    TIRED = "😓 Tired"

# fmt: on
