#!/usr/bin/env python3
"""Generate notion_schema.py and _schema.ts from schema.yaml.

Usage:
    python scripts/gen_schema.py

Reads schema.yaml at the project root and emits:
  - src/gym_coach/notion_schema.py   (Python constants)
  - web/api/_schema.ts               (TypeScript constants + literal types)
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).parent.parent
SCHEMA_FILE = REPO_ROOT / "schema.yaml"
PY_OUT = REPO_ROOT / "src" / "gym_coach" / "notion_schema.py"
TS_OUT = REPO_ROOT / "web" / "api" / "_schema.ts"

HEADER_PY = '"""Notion schema constants.\n\nAUTO-GENERATED by scripts/gen_schema.py — do not edit manually.\nEdit schema.yaml and run: python scripts/gen_schema.py\n"""'
HEADER_TS = "// AUTO-GENERATED by scripts/gen_schema.py — do not edit manually.\n// Edit schema.yaml and run: python scripts/gen_schema.py"


def snake_to_upper(key: str) -> str:
    return key.upper()


def gen_python(schema: dict) -> str:
    lines = [
        HEADER_PY,
        "",
        "# fmt: off",
        "",
    ]

    # ── PROPS: top-level Workout Log property names ──────────────
    lines += ["class PROPS:", '    """Top-level Workout Log property names."""']
    for key, prop in schema["workout_log"]["properties"].items():
        const = snake_to_upper(key)
        name = prop["notion_name"]
        lines.append(f'    {const} = "{name}"')
    lines.append("")

    # ── TRACK: Weight Tracking Log column names ──────────────────
    lines += ["class TRACK:", '    """Weight Tracking Log child database column names."""']
    set_cols: list[str] = []
    for key, col in schema["weight_tracking_log"]["columns"].items():
        const = snake_to_upper(key)
        name = col["notion_name"]
        lines.append(f'    {const} = "{name}"')
        if key.startswith("set_") and key[4:].isdigit():
            set_cols.append(f'"{name}"')
    # Convenience tuple for loop access: TRACK.SET_COLS[i-1]
    lines.append(f"    SET_COLS: tuple[str, ...] = ({', '.join(set_cols)},)")
    lines.append("")

    # ── DAY_LABELS: Day Type select values ───────────────────────
    lines += ["class DAY_LABELS:", '    """Notion Day Type select values (key → notion select name)."""']
    for key, label in schema["day_labels"].items():
        const = snake_to_upper(key)
        lines.append(f'    {const} = "{label}"')
    lines.append("")

    # ── Per-select literal classes ───────────────────────────────
    select_props = {
        k: v for k, v in schema["workout_log"]["properties"].items()
        if v["type"] == "select" and k not in ("day_type", "difficulty")
    }
    for key, prop in select_props.items():
        class_name = "".join(w.capitalize() for w in key.split("_"))
        lines += [f"class {class_name}Values:", f'    """Allowed select values for \'{prop["notion_name"]}\'."""']
        for opt in prop["options"]:
            # Derive a clean constant name: strip leading emoji + spaces
            stripped = opt.strip()
            # Remove leading non-ascii chars and spaces
            ascii_start = next((i for i, c in enumerate(stripped) if c.isascii() and c.isalpha()), 0)
            label = stripped[ascii_start:].strip().upper().replace(" ", "_").replace("-", "_")
            lines.append(f'    {label} = "{opt}"')
        lines.append("")

    lines.append("# fmt: on")
    lines.append("")
    return "\n".join(lines)


def gen_typescript(schema: dict) -> str:
    lines = [
        HEADER_TS,
        "",
        "// ─── Top-level Workout Log property names ──────────────────",
        "export const PROPS = {",
    ]
    for key, prop in schema["workout_log"]["properties"].items():
        const = snake_to_upper(key)
        name = prop["notion_name"]
        lines.append(f'  {const}: "{name}",')
    lines += ["} as const;", ""]

    # ── TRACK ────────────────────────────────────────────────────
    lines += [
        "// ─── Weight Tracking Log column names ─────────────────────",
        "export const TRACK = {",
    ]
    set_cols: list[str] = []
    for key, col in schema["weight_tracking_log"]["columns"].items():
        const = snake_to_upper(key)
        name = col["notion_name"]
        lines.append(f'  {const}: "{name}",')
        if key.startswith("set_") and key[4:].isdigit():
            set_cols.append(f'"{name}"')
    lines += ["} as const;", ""]

    # SET_COLS convenience tuple
    lines += [
        "// Convenience array for loop access: TRACK_SET_COLS[i - 1]",
        f"export const TRACK_SET_COLS = [{', '.join(set_cols)}] as const;",
        "",
    ]

    # ── DAY_LABELS ───────────────────────────────────────────────
    lines += [
        "// ─── Day Type select values ────────────────────────────────",
        "export const DAY_LABELS = {",
    ]
    for key, label in schema["day_labels"].items():
        lines.append(f'  {key}: "{label}",')
    lines += ["} as const;", ""]

    # ── Reverse map ──────────────────────────────────────────────
    lines += [
        "export const DAY_TYPE_TO_KEY: Record<string, string> = Object.fromEntries(",
        "  Object.entries(DAY_LABELS).map(([k, v]) => [v, k])",
        ");",
        "",
    ]

    # ── Literal union types from select options ──────────────────
    lines.append("// ─── Select value literal union types ─────────────────────")
    select_props = {
        k: v for k, v in schema["workout_log"]["properties"].items()
        if v["type"] == "select"
    }
    type_map = {
        "energy": "EnergyValue",
        "knee_comfort": "KneeComfortValue",
        "mood": "MoodValue",
        "difficulty": "DifficultyValue",
        "day_type": "DayTypeValue",
    }
    for key, prop in select_props.items():
        type_name = type_map.get(key, "".join(w.capitalize() for w in key.split("_")) + "Value")
        opts = " | ".join(f'"{o}"' for o in prop["options"])
        lines.append(f"export type {type_name} = {opts};")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    if not SCHEMA_FILE.exists():
        print(f"Error: {SCHEMA_FILE} not found", file=sys.stderr)
        sys.exit(1)

    schema = yaml.safe_load(SCHEMA_FILE.read_text(encoding="utf-8"))

    py_code = gen_python(schema)
    PY_OUT.write_text(py_code, encoding="utf-8")
    print(f"✅ Written {PY_OUT.relative_to(REPO_ROOT)}")

    ts_code = gen_typescript(schema)
    TS_OUT.write_text(ts_code, encoding="utf-8")
    print(f"✅ Written {TS_OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
