// AUTO-GENERATED by scripts/gen_schema.py — do not edit manually.
// Edit schema.yaml and run: python scripts/gen_schema.py

// ─── Top-level Workout Log property names ──────────────────
export const PROPS = {
  WORKOUT_NAME: "Workout Name",
  DATE: "Date",
  DAY_TYPE: "Day Type",
  DURATION: "Duration",
  DIFFICULTY: "Difficulty",
  ENERGY: "Energy",
  KNEE_COMFORT: "Knee Comfort",
  MOOD: "Mood",
  SAUNA: "Sauna",
  WORKOUT_NOTES: "Workout Notes",
} as const;

// ─── Weight Tracking Log column names ─────────────────────
export const TRACK = {
  EXERCISE: "Exercise",
  SUGGESTED: "Suggested",
  SETS_X_REPS: "Sets x Reps",
  SET_1: "Set 1",
  SET_2: "Set 2",
  SET_3: "Set 3",
  SET_4: "Set 4",
  NOTES: "Notes",
} as const;

// Convenience array for loop access: TRACK_SET_COLS[i - 1]
export const TRACK_SET_COLS = ["Set 1", "Set 2", "Set 3", "Set 4"] as const;

// ─── Day Type select values ────────────────────────────────
export const DAY_LABELS = {
  tuesday:   "Tuesday - Upper Push",
  wednesday: "Wednesday - Upper Pull",
  friday:    "Friday - Legs",
  sunday:    "Sunday - Bachata",
} as const;

export const DAY_TYPE_TO_KEY: Record<string, string> = Object.fromEntries(
  Object.entries(DAY_LABELS).map(([k, v]) => [v, k])
);

// ─── Select value literal union types ─────────────────────
export type DayTypeValue = "Tuesday - Upper Push" | "Wednesday - Upper Pull" | "Friday - Legs";
export type DifficultyValue = "1" | "2" | "3" | "4" | "5";
export type EnergyValue = "⚡ High" | "😐 Medium" | "😴 Low";
export type KneeComfortValue = "✅ No pain" | "⚠️ Mild discomfort" | "🛑 Pain";
export type MoodValue = "😊 Great" | "😌 Good" | "😐 Neutral" | "😓 Tired";
